### ISSUE TITLE
Doesn't work with identical jobs

### ISSUE THREAD

**Issue by penman** [gocardless/rspec-activejob#30] opened 2016-08-09 11:28 UTC
I have a ScoringJob that is created whenever a record is created or update.
I want to test that the job is enqueued when the record is updated.

The test looks something like this:

```ruby
it "enqueues a scoring job when updated" do
  record = create_record # enqueues one instance of the scoring job
  expect { record.update!(value: record.value + 1) }.
    to enqueue_a(ScoringJob).with(global_id(record))
end
```

This test fails, even though my code is correct, because the job enqueued inside the `expect` block is identical to a job that already exists.

I've tracked the problem down to [`RSpec::ActiveJob::Matchers::EnqueueA#new_jobs`](https://github.com/gocardless/rspec-activejob/blob/master/lib/rspec/active_job/enqueue_a.rb#L139-L141):

```ruby
def new_jobs
  enqueued_jobs - @before_jobs
end
```

The problem here is `Array#-`, which removes _all_ matching elements.
The correct behaviour would be to only remove the first element matching each item in `@before_jobs`.

**Comment by isaacseymour** [comment] 2016-08-09 13:39
Looks like this is a duplicate of #28 - could you check if that patch fixes this for you?

**Comment by penman** [comment] 2016-08-09 14:44
Oh, yes, I forgot to check PRs before I opened my issue.

I refactored that test, and don't really have the original around any more, but I am 95% sure that would have fixed it.

**Comment by isaacseymour** [comment] 2016-08-09 14:49
👌 

Other thing to note is that you might want to consider using rspec-rails, which includes the `have_enqueued_job` and `have_been_enqueued` matchers in 3.5+ (see #31 )

**Comment by penman** [comment] 2016-08-09 15:19
Oh, cool! Thanks.

**Comment by petehamilton** [comment] 2016-08-10 18:00
Cheers @isaacseymour. @penman I figure you're fine with us closing this issue now, if not just shout 😄

**Closed by petehamilton** 2016-08-10 18:00 UTC
